// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEsjg7XKFaXOEeNaAzoGsnp5PoX2QAL98',
    appId: '1:684731288764:android:710ba9adf64b894eb814b9',
    messagingSenderId: '684731288764',
    projectId: 'shadow-chat-dc374',
    storageBucket: 'shadow-chat-dc374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMB9qwcdxp0uPoVevbbcTbDqLfFYo6qnE',
    appId: '1:684731288764:ios:4e0b6ddac398ce8cb814b9',
    messagingSenderId: '684731288764',
    projectId: 'shadow-chat-dc374',
    storageBucket: 'shadow-chat-dc374.firebasestorage.app',
    iosBundleId: 'com.example.shadowChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMB9qwcdxp0uPoVevbbcTbDqLfFYo6qnE',
    appId: '1:684731288764:ios:4e0b6ddac398ce8cb814b9',
    messagingSenderId: '684731288764',
    projectId: 'shadow-chat-dc374',
    storageBucket: 'shadow-chat-dc374.firebasestorage.app',
    iosBundleId: 'com.example.shadowChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClGvEruoEK4ScRECLls9m514R_qOMqcZA',
    appId: '1:684731288764:web:ca5ba185505ac789b814b9',
    messagingSenderId: '684731288764',
    projectId: 'shadow-chat-dc374',
    authDomain: 'shadow-chat-dc374.firebaseapp.com',
    storageBucket: 'shadow-chat-dc374.firebasestorage.app',
    measurementId: 'G-BWLC0Z7TFN',
  );

}